- Source/AssemblyInfo.cs
- Source/AssemblyInfo.cs.meta
- Source/Base/Variable/ScriptableObjectVariable.cs
- Source/Base/Variable/ScriptableObjectVariableBase.cs
- Source/Editor/CodeGenerator.cs
- Source/Editor/GameEventEditor.cs
- Source/Extensions/IListExtensions.cs
- Source/Extensions/IListExtensions.cs.meta
- Source/MonoHooks/OnButtonClickHook.cs
- Source/Types/Float/FloatVariable.cs
- Source/Types/GameObject/GetUnusedGameObject.cs
- Source/Types/Int/IntVariable.cs
- Source/Utils/RuntimeConstants.cs
- Source/Utils/RuntimeConstants.cs.meta
This PR does a certain amount of housecleaning to removed redundant and unused types and methods. No functional changes should result in existing code in this library from this.
* Removed redundant interfaces IWithValue<T> and IWithOldValue<T> as they and their methods are unused.
* Removed redundant extensions and util classes/methods as they are unused by anything in the library
* Created AssemblyInfo.cs file to contain [assembly] attributes to expose internal types and methods to the UnityAtomsEditor assembly. This makes it easier to keep non-user facing code as internal, but still expose it for Editor usage.
* Removed AtomsLogger as this class does not add any value to the library. Some situations where it was being used in to warn of missing components such as OnButtonClickHook were …
> Removed redundant code

- Source/UnityAtoms.asmdef
- package.json
fixing #45 where in newer unity versions all ugui stuff is in an own package, which needed to be added in the assembly defintion.
**note**: I'd rather add this changes to its own branch (e.g. canary-2019.2 or whatever) because it could give problems with current stable unity versions (2018.3 or the 2018.4 LTS when it arrives) 
but when creating a pull request github does not allow to create a new target branch
> Unity Atoms 2019.2+ support

- README.md
- website/core/Footer.js
Just created a Discord channel for Unity Atoms (see #59). This PR adds a link to the Discord channel in `README.md` and in the website's footer.
> Add discord link to docs

- Packages/Core/Runtime/References/AtomReference.cs
In order to set the corresponding value depending on _usage
> Setter to AtomReference's Value was added 

- Packages/Core/Editor/Drawers/AtomReferenceDrawer.cs
> Fix #87: AtomReference Drawer is always 1 line, even if the object needs more

- CHANGELOG.md
- Packages/MonoHooks/Runtime/Hooks/OnTriggerHook.cs
OnTriggerHook was named "OnTriggerStayHook" and it was therefore not possible to use it. This naming bug is corrected in this PR.
> Bux fix - name OnTriggerHook class properly.

- Examples/Packages/manifest.json
- Packages/Core/Editor/Drawers/AtomDrawer.cs
- Packages/Core/Editor/Generator/RegenerateAllAtoms.cs
- Packages/MonoHooks/Runtime/MamboJamboStudios.UnityAtomsMonoHooks.Runtime.asmdef
- Fixed MonoHooks asmdef reference to Core asmdef was broken.
- Fixed dependancy issue for Package Manager.
- Removed Generator function in version 2018.4.
> Unity v2018.4 Support

- Packages/Core/Editor/Generator/RegenerateAllAtoms.cs
- Packages/Core/Runtime/Utils/Runtime.cs
This PR is removing leftovers from an old commit that is causing issues when generating atoms. Since the variable `_isUnityAtomsRepo` by default is set to false it sometimes falsely is returning false even though it should return true. By making IsUnityAtomsRepo none settable the issue is resolved.
> IsUnityAtomsRepo should never be set

- Packages/Core/Editor/Drawers/VariableDrawer.cs
This PR fixes #104. The solution is using a smilar strategy as how the AtomReferenceDrawer is solving laying out its GUI horizontally.
> Fix indentation bug in variable drawer

- Packages/Core/Runtime/Variables/AtomBaseVariable.cs
- Packages/Core/Runtime/Variables/AtomVariable.cs
- Packages/Core/Runtime/Variables/Collider2DVariable.cs
- Packages/Core/Runtime/Variables/ColliderVariable.cs
- Packages/Core/Runtime/Variables/EquatableAtomVariable.cs
- Packages/Core/Runtime/Variables/GameObjectVariable.cs
- docs/introduction/generator.md
This PR addresses #95. Besides that it changes the name on the `AreEquals` function to `ValueEquals`.
> Fix variable equality issues

- Packages/FSM/Runtime/FiniteStateMachine/FiniteStateMachine.cs
Fix for #176.
Turns out when updating FSMs, if a state has a Sub FSM, its Value is updated to be the Sub FSM's Value, and not the base FSM's Value, thereby rendering `submachine` null.
> Fix Sub FSM Value issue

- Packages/Core/Editor/Drawers/AtomDrawer.cs
It's annoying when new Atom, Event is created in root Asset directory. It's a small improvement that adds support for creating a new .asset file in the current ScriptableObject directory if SO is selected. If GameObject on the scene is selected it creates in root Asset folder, because it's impossible to detect directory.
#185
> Creating new atom in current directory improvement

- Packages/Core/Runtime/Variables/AtomVariable.cs
This may not be the optimal solution but It seems working and we can think this as a workaround until we find a better approach.
**Important Note:** If you enable the "Enter Pay Mode" feature in Unity, you have to restart the editor to make this workaround work.
> Add workaround for "Enter Play Mode" feature to enable initial values

- Packages/Core/Runtime/Events/AtomEvent.cs
- Packages/Core/Runtime/Events/AtomEventBase.cs
UnregisterAll did not unregister for listeners of OnEventNoValue.
this addresses https://github.com/AdamRamberg/unity-atoms/issues/200
> [Bugfix] #200 (UnregisterAll for AtomEventBase)

- Packages/Core/Editor/Editors/AtomFolderEditor.cs
- Packages/Core/Editor/Editors/AtomFolderEditor.cs.meta
- Packages/Core/Editor/Editors/AtomGeneratorEditor.cs
- Packages/Core/Editor/Editors/AtomGeneratorEditor.cs.meta
- Packages/Core/Editor/Generator/AtomGenerator.cs
- Packages/Core/Editor/Generator/AtomGenerator.cs.meta
- Packages/Core/Editor/Generator/RegenerateAllAtoms.cs
which scripts to generate can now be added to assets.
I've just added it ontop of the current system, so there are some redundancies.
also it has to be tested if this would regenerate assets in packages.
it also contains an custom inspector for Folders, if a folder contains "Atom" it shows a button to generate a new generation file.
not sure if we should keep this, but it could be a nice user workflow improvement. e.g. for typical used atoms (IntVariable / FloatVariable)
>  asset based atoms generation

- Packages/Core/Runtime/Listeners/AtomEventReferenceListener.cs
The EventReference isn't initialized as null anymore, but require a default constructor as generic constraint.
https://github.com/AdamRamberg/unity-atoms/issues/196
_______________
This PR will introduce a new constraint, most AtomBaseEventReference, as a default constructor is now required. on the other hand: all built-in AtomBaseEventReference subclasses do fulfill the requirement.
One could argue that the intended use is via the editor and unitys serialization system instead of via code, which would mean it isn't a bug, but instead a design decision. (I - personally - would see it as a bug, though)
> [BugFix] #196 (EventReferenceListener null reference)

- Packages/Core/Runtime/References/AtomReference.cs
Some scripts or checks might be used to see whether or not a Reference has been assigned.
this method allows to do so.
> Added for AtomReference a check to see if an Atom is actually assigned.

- Packages/Core/Editor/Editors/AtomGeneratorEditor.cs
- Packages/Core/Runtime/EventReferences/AtomEventReference.cs
- Packages/Core/Runtime/Interfaces/IGetOrCreateEvent.cs
- Packages/Core/Runtime/Interfaces/IGetOrCreateEvent.cs.meta
- Packages/Core/Runtime/VariableInstancers/AtomVariableInstancer.cs
- Packages/Core/Runtime/Variables/AtomVariable.cs
- Trigger initial events for instancers
- Clean up event name for events instantiated at runtime
- Added properties to check if an event is set or not on a variable. This is useful in order to not accidentally create an event at runtime when just checking if it is null or not.
- Added logic to clean up events instantiated at runtime.
Fixes #210
> Trigger initial events for instancers

- docs/introduction/faq.md
Noticed that the Discord invite link in the FAQ was broken, so updating it to match the one in the footer.
_Not sure if you need a Github issue opened for a PR this small, happy to make one if required._
> Fix the Discord link in the FAQ

- Packages/Core/Runtime/References/AtomReference.cs
- Packages/Core/Runtime/VariableInstancers/AtomBaseVariableInstancer.cs
See #240 
should fix a nullref exception when checking the Value of a VariableInstancer on a Reference might lead to null reference exceptions
> fixing #240 - Value of a VariableInstancer in EditMode leads to NullRef

- website/package-lock.json
Reverts unity-atoms/unity-atoms#244
This PR should have been merged into canary.
> Revert "Bump highlight.js from 9.15.10 to 9.18.5 in /website"

- Packages/Core/Editor/Drawers/AtomDrawer.cs
Will make the create button a bit easier to use.
- When the Create button is clicked, the naming field gets auto-focus.
- If the Create button is used in a reference field, the PrefixLabel will no longer clog the inspector.
- The confirm create and deny create buttons also get triggered when return (enter) or escape is pressed respectively.
> Create button ease of use

- Packages/BaseAtoms/package.json
- Packages/Core/package.json
- Packages/Mobile/package.json
- Packages/MonoHooks/package.json
Dependencies to built-in packages and other Atoms packages are now correctly specified.
Fixes #283 .
> Fixed specifying package dependencies

- Packages/MonoHooks/Runtime/Hooks/OnAwakeHook.cs
- Packages/MonoHooks/Runtime/Hooks/VoidHook.cs
Reverts unity-atoms/unity-atoms#272 because it is a breaking change and belongs into v5.
> Revert "#271 Use event references in VoidHook and OnAwakeHook"

- CHANGELOG.md
- Packages/BaseAtoms/Runtime/Collections/AtomCollection.cs
Calling OnAfterDeserialize again, as Collection may use StringConstant or StringVariable as key, and Unity doesnt ensures execution order in Scriptable Objects
As such is possible that the Collection is called before its keys are ready to be used.
On OnEnable, all atoms are supposed to already have been initialized, and calling OnAfterDeserialize, will fix any issue with not ready keys 
#299
> Fixed collection deserialization problem.

- Packages/Core/Editor/Editors/Variables/AtomVariableEditor.cs
Ulong was deserialized to a System32 int. The solution was to use the same fix as for the Double type which was serialized to a float. I guess more of these issues might appear in the future so then this fix might become quite a long bit of code
> fix #254 [BUG] ulong variable throws error when the value being edited in play mode.

- Packages/Core/Runtime/EventInstancers/AtomEventInstancer.cs
- Packages/Core/Runtime/VariableInstancers/AtomBaseVariableInstancer.cs
When the GameObject that contained the event/variable instancer was disabled and re enabled, a new _inMemoryCopy was instantiated and the old one overriden. The listeners however were still listening to the overriden one. By checking if theres already an _inMemoryCopy in the scene this bug can be solved.
One thing that i'm not sure what to do with. If the user destroys the event/variable instancer component or GameObject, do we have to Unregister these listener as Unity Atoms or do we let this "error" up to the user? Also what do we do with the listeners that now won't listen to something anymore?
> Fix #268 [BUG] Void Event Instancer stops working after deactivate / activate cycle

- Packages/Core/Runtime/VariableInstancers/AtomVariableInstancer.cs
The null check on Base events in AtomVariableInstancer didn't account for Base itself and didnt create runtime AtomEvents.
> Fix #255 AtomVariableInstancer assumes Base != null

- Packages/Core/Runtime/Variables/AtomVariable.cs
There was an extra underscore in the name of Changed With History runtime generated event.
> Remove extra underscore from ChangedHistoryEvent name

- Packages/Core/Editor/Extensions/SerializedPropertyExtensions.cs
The value property inside an AtomVariable is used with the Unity JsonUtility to make sure changes are working properly. There was no check for the System.NonSerialized attribute. This made it igonre that attribute only on the AtomVariable value property. By adding this check the System.NonSerialized attrbute also gets respected in the value. It was already working with this attribute on the C# action in the initialValue.
> fix #237 Drawer tries to create field for public Action

- Packages/Tags/Runtime/AtomTags.cs
in case no object was tagged FindByTag threw an exception instead of returning null.
> fix #305 empty list of tagged objects throws NRE

- docs/introduction/installation.md
added to prevent unity from raising missing dependency error.
> add missing scoped registry in install docs

- .github/workflows/activation.yml
This workflow needs to be executed from the master branch. It is necessary to activate a license for Unity to execute unit tests in the future.
> Workflow for acquiring Unity activation file

- Packages/Core/Runtime/Variables/AtomVariable.cs
This commit is a possible solution for #269
When using an Event Reference Listener with a variable, GetOrCreateEvent() is sometimes called after TriggerInitialEvents(). This commit is a way to solve this.
> #269 Fix ChangedOnOnEnable not triggered

- Packages/Core/Editor/Drawers/AtomBaseReferenceDrawer.cs
The display of an AtomReference would act a bit weird if the Atom was of e.g. a serializable class.
Old: open button is displayed weirdly on top of the selection button.
New: open button is displayed at the original position. 
Since the EditorGUI.PropertyField in question has GUIContent.none, I do not expect this to break any other displays.
> Fix hasChildren display in AtomReferences

- Packages/Core/Runtime/StackTrace/StackTraceEntry.cs
fixes the issue: 
https://github.com/unity-atoms/unity-atoms/issues/328
another option for the fix would be to return an Action/Func which then only creates a StackEntry in https://github.com/unity-atoms/unity-atoms/blob/85bbaa03bb29b16776d631c033d8b514a32472b3/Packages/Core/Runtime/StackTrace/StackTraces.cs#L12 if needed. 
but this would actually change the method heads of public methods and thus would be a breaking change, requiring a major version upgrade.
thus this simple fix of returning null 
( also, the Action or Func object itself would also allocate memory, this could be circumvented with a custom `ref struct Func`, .... but at this point it would be totally overengineered)
> fixing unnecessary allocations when debug mode disabled

- README.md
Unfortunately Casey-Hofland was unable to continue as a maintainer. This PR updates the README.md to reflect that.
> Remove Casey-Hofland from list of maintainers

- Packages/Core/Runtime/EventReferences/AtomEventReference.cs
As suggested by @soraphis changed that the Event reference listener doesn't just throw a null reference exception everywhere. I added a check for Atoms debug mode. In debug mode the user gets notified of the null reference which he has. But in runtime/production this exception doesn't get thrown.
I chose for a NRE because on clicking this error the connected gameObject gets pinged. This doesn't happen when using the Unity Debug class.
> Fix #321 NRE when Event Reference Listeners event reference is not set

- Packages/Core/Runtime/StackTrace/StackTraceEntry.cs
fixes #347 
> PR https://github.com/unity-atoms/unity-atoms/pull/329 made the projects unable to compile in builds:
> 
> as the lines require AtomPreferences.IsDebugModeEnabled
> https://github.com/unity-atoms/unity-atoms/blob/v4.4.4/Packages/Core/Runtime/StackTrace/StackTraceEntry.cs#L63=
> 
> but due to conditional compilation:
> https://github.com/unity-atoms/unity-atoms/blob/v4.4.4/Packages/Core/Runtime/Preferences/AtomsPreferences.cs#L1=
> 
> this does not exist in builds
> #347 [fix]: conditional compilation for EDITOR only code

- Packages/Core/Editor/Drawers/AtomBaseReferenceDrawer.cs
fixes #353 and #357
The code before https://github.com/unity-atoms/unity-atoms/pull/289 has handled properties with custom-one-line-drawers (like Vector3) correctly, but did not handle custom structs - when collapsed - correctly.
this fix is the best of both worlds: 
- Get the property height of the property if it would be expanded, 
- then decided based upon whether or not it _would_ occupy multiple lines.
this also fixes the broken StringReferences mentioned in (#357)
> fix: #353 "Vector2/3 reference not properly showing"

- Packages/Core/Runtime/Variables/AtomVariable.cs
this addresses #349 and fixes an issue introduced with #303 
when starting the runtime without changed event, it would set the "_changedInstantiatedAtRuntime" to true.
OnDisable is only called if you hit play again and are about to enter the playmode again, which then RESETS all your changes (e.g. assigning an event in edit time) to null. 
the alternative would be to address this in the custom editor drawer, to set _changedInstantiatedAtRuntime to false again when _changed was set.
but I found that the OnDisable was not needed, as the values where already set back when leaving playmode and in the build (which i have not tested!! it wouldn't matter anyways since OnDisable is only called if the memory is freed altogether)
> removed ondisable method, to fix #349

- Packages/FSM/Runtime/FiniteStateMachine/FiniteStateMachineMonoHook.cs
prevents FiniteStateMachineMonoHook singleton from being unloaded
fixes #385
> FiniteStateMachineMonoHook unload fix

- Packages/Core/Editor/Editors/AtomGeneratorEditor.cs
- Packages/Core/Editor/Generator/AtomGenerator.cs
fix: pasting FullQualifiedName in the generators text field, not picking up the actual type
closes #408
> FIX: Using TextField in AssetGenerator does not work as expected

- Packages/Core/Editor/Drawers/AtomDrawer.cs
- Packages/Core/Editor/Utils/AtomNameUtils.cs
- Packages/Core/Editor/Utils/AtomNameUtils.cs.meta
https://youtu.be/_seSt3tMZdU 
Currently the implementation suggests a name for a new Event or variable when created with the 'Create' button. If the parent of the property is a BaseAtom (Variable, valuelist, FSM etc) the naming structure is: "name of variable/valuelist/FSM" + name of property ("Changed" when you add a variable changed event) + type of Event/variable ("BoolEvent" for example). When you try to create a second default named event the system will add a number at the end just like it is with duplicating GameObjects. Everything can be seen in the video above. 
There are some occasions where this default naming scheme can be a bit weird, as you can see with SetIntVariableValue as an example. However if you create custom names for a variable things get quite clear. If there are …
> #67 [FEATURE] Set event name suggestion on Variable Changed event creation 

- Packages/Core/Runtime/Events/AtomEvent.cs
- Packages/Core/Runtime/ValueLists/AtomValueList.cs
- Packages/Core/Runtime/ValueLists/BaseAtomValueList.cs
- Packages/Core/Runtime/Variables/AtomVariable.cs
Fixes: #417
Objects might be null (as they are unity objects) after an asset is deleted (or an AtomInstancer deleted it's runtime asset) - so these assets would through NRE when resetting with disabled domain reload.
the NRE would also prevent the other objects to reset correctly
> Handling dead references when resetting objects.

- Packages/Core/Runtime/Events/AtomEvent.cs
- Packages/Core/Runtime/ValueLists/AtomValueList.cs
- Packages/Core/Runtime/Variables/AtomVariable.cs
This PR adds appropriate `UNITY_EDITOR` compiler flags in order to solve the error: 
`The name '_instances' does not exist in the current context`
> Fix "The name '_instances' does not exist in the current context"

- Packages/Core/Editor/Drawers/AtomBaseReferenceDrawer.cs
- Packages/Core/Editor/Editors/Variables/AtomVariableEditor.cs
Reverts the changes in #440 / #437 for older Unity versions (2022.1 or older) since it breaks the drawer in those versions. 
**Before change (2021.1.6f1)**
**After change (2021.1.6f1)**
> Fix value field height in reference drawer for older Unity versions

- Packages/Core/Runtime/Preferences/AtomsPreferences.cs
- Packages/Core/Runtime/StackTrace/StackTraceEntry.cs
- Packages/Core/Runtime/StackTrace/StackTraces.cs
fixes: #434 
fix: memory allocations due to boxing when creating a StackTraceEntry with disabled DebugMode.
fix: slow repeaded lookups of EditorPrefs for determining DebugMode
> Reduced debug overhead of Events

- Packages/Core/Editor/Generator/GeneratorEditor.cs
With 4.4.8, removing, for example, `Pair` from Generator, would produce this warning:
Saying that, for example, `Event Instancer` depends on `Pair`, implying it got disabled, but it actually wasn't. It was `Pair Event Instancer` that got disabled, but was messaged incorrectly.
With this PR, that is fixed to:
To properly indicate what is being disabled.
> [Generator] Fix invalid dependency warning

- Packages/Core/Runtime/Events/AtomEvent.cs
presently, only the `AtomListener`-based overload of `Register` accepts a flag to skip the replay buffer. this adds the flag to the `Action`-based overload. it needed to be implemented as an overload, rather than an optional arg, because the current `Action`-overload is used as a method reference internally.
> add `replayEventsBuffer` option to `Action`-based `Register` call

- Packages/Core/Runtime/ValueLists/AtomValueList.cs
As a developer, I want to reference an `AtomValueList` asset in a UnityEvent and modify it. `AtomValueList` already exposes a `Remove` but since it returns a `bool`, Unity will not display it as a function. This wraps the Remove function with a `void` so it can be called as a serialized function.
> Add RemoveItem for AtomValueList for usage in UnityEvents

- Packages/Core/Runtime/EventReferences/AtomBaseEventReference.cs
Closes: #443
- Also instead of raising an exception we just `Debug.LogError` whenever the `Event` is null to not disturb any code that is followed by the event call. The question of whether or not to raise an exception is talked about in a [discord channel](https://discord.com/channels/640589221136171020/643165315546742785/1168946487783329921)
> #443 [FEATURE] AtomBaseEventReference to have Raise methods inside
