- Source/Editor/CodeGenerator.cs
UIElements are not experimental anymore.
This gets it right for 2019.1 and 2018.3
> UIElements Fix for 2019.1

- Source/Base/ScriptableObjectReference.cs
- Source/Base/SetVariableValue.cs
- Source/Editor/CodeGenerator.cs
- Source/Editor/ReferenceDrawer.cs
- Source/Editor/SceneFieldDrawer.cs
- Source/Editor/SceneFieldDrawer.cs.meta
- Source/Types/Bool/BoolReference.cs
- Source/Types/Color/ColorReference.cs
- Source/Types/Float/FloatReference.cs
- Source/Types/GameObject/GameObjectReference.cs
- Source/Types/Int/IntReference.cs
- Source/Types/SceneField.meta
- Source/Types/SceneField/SceneField.cs
- Source/Types/SceneField/SceneField.cs.meta
- Source/Types/SceneField/SceneFieldAction.cs
- Source/Types/SceneField/SceneFieldAction.cs.meta
- Source/Types/SceneField/SceneFieldConstant.cs
- Source/Types/SceneField/SceneFieldConstant.cs.meta
- Source/Types/SceneField/SceneFieldReference.cs
- Source/Types/SceneField/SceneFieldReference.cs.meta
- Source/Types/SceneField/SceneFieldVariable.cs
- Source/Types/SceneField/SceneFieldVariable.cs.meta
- Source/Types/String/StringReference.cs
- Source/Types/Vector2/Vector2Reference.cs
- Source/Types/Vector3/Vector3Reference.cs
addressing #37 
adds a SceneField Type to use scene fields in the Inspector.
adds AtomVariables Constants and References for this new type
> SceneField implementation

- Packages/Core/Editor/Drawers/Constants/BoolConstantDrawer.cs
- Packages/Core/Editor/Drawers/Constants/Collider2DConstantDrawer.cs
- Packages/Core/Editor/Drawers/Constants/ColliderConstantDrawer.cs
- Packages/Core/Editor/Drawers/Constants/ColorConstantDrawer.cs
- Packages/Core/Editor/Drawers/Constants/FloatConstantDrawer.cs
- Packages/Core/Editor/Drawers/Constants/GameObjectConstantDrawer.cs
- Packages/Core/Editor/Drawers/Constants/IntConstantDrawer.cs
- Packages/Core/Editor/Drawers/Constants/StringConstantDrawer.cs
- Packages/Core/Editor/Drawers/Constants/Vector2ConstantDrawer.cs
- Packages/Core/Editor/Drawers/Constants/Vector3ConstantDrawer.cs
- Packages/Core/Editor/Drawers/VariableDrawer.cs
- Packages/Core/Editor/Drawers/VariableDrawer.cs.meta
- Packages/Core/Editor/Drawers/Variables/BoolVariableDrawer.cs
- Packages/Core/Editor/Drawers/Variables/Collider2DVariableDrawer.cs
- Packages/Core/Editor/Drawers/Variables/ColliderVariableDrawer.cs
- Packages/Core/Editor/Drawers/Variables/ColorVariableDrawer.cs
- Packages/Core/Editor/Drawers/Variables/FloatVariableDrawer.cs
- Packages/Core/Editor/Drawers/Variables/GameObjectVariableDrawer.cs
- Packages/Core/Editor/Drawers/Variables/IntVariableDrawer.cs
- Packages/Core/Editor/Drawers/Variables/StringVariableDrawer.cs
- Packages/Core/Editor/Drawers/Variables/Vector2VariableDrawer.cs
- Packages/Core/Editor/Drawers/Variables/Vector3VariableDrawer.cs
- Packages/Core/Editor/Generator/Resources/UA_Template_AtomDrawer__Constant.txt
- Packages/Core/Editor/Generator/Resources/UA_Template_AtomDrawer__Variable.txt
fixing #74 
this time, i made the PR targeting canary - forgot this last time. d'oh
> Variable and Constant Drawers show a preview value

- Packages/Core/Runtime/Actions/AtomAction.cs
- Packages/Core/Runtime/Actions/VoidAction.cs
- Packages/Core/Runtime/Events/AtomEvent.cs
- Packages/Core/Runtime/Listeners/AtomListener.cs
- Packages/Core/Runtime/Listeners/IAtomListener.cs
This PR is related to #84 Just last commit
> #84 parameterless atom listener

- README.md
- docs/introduction/quick-start.md
> docs: add installation options and badges

- Packages/Tags/Runtime/AtomTags.cs
- Packages/Tags/Tests/Runtime/AtomTagsTests.cs
ref: #101
Fixed Remove tag and and Fixed tests to cover that function.
> Fix Remove Tag from AtomTags and Fix Remove Tag Test

- Packages/Core/Editor/Generator/Resources/UA_Template__Reference.txt
- Packages/Core/Runtime/References/BoolReference.cs
- Packages/Core/Runtime/References/Collider2DReference.cs
- Packages/Core/Runtime/References/ColliderReference.cs
- Packages/Core/Runtime/References/ColorReference.cs
- Packages/Core/Runtime/References/EquatableAtomReference.cs
- Packages/Core/Runtime/References/FloatReference.cs
- Packages/Core/Runtime/References/GameObjectReference.cs
- Packages/Core/Runtime/References/IntReference.cs
- Packages/Core/Runtime/References/StringReference.cs
- Packages/Core/Runtime/References/Vector2Reference.cs
- Packages/Core/Runtime/References/Vector3Reference.cs
- Packages/Mobile/Runtime/References/TouchUserInputReference.cs
- Packages/SceneMgmt/Runtime/References/SceneFieldReference.cs
> Add constructor with value to Reference classes

- Packages/Core/Runtime/Base/BaseAtom.cs
- Packages/Core/Runtime/Listeners/AtomBaseListener.cs
> Developer Description changed from Multiline to TextArea attribute

- Packages/Core/Runtime/Variables/AtomVariable.cs
brought up by this post here: https://github.com/AdamRamberg/unity-atoms/issues/136#issuecomment-622447714
> Changes in GetEvent implementation to allow inheritance

- Packages/Core/Editor/Generator/GeneratorEditor.cs
> Fix code generation bug

- docs/introduction/generator.md
Add the [Serializable] attribute in the documentation for the generator example
> Add the [Serializable] attribute in the doc

- Packages/Core/Runtime/Variables/AtomVariable.cs
> Added forceEvent parameter for SetValue function on AtomVariable

- Packages/Core/Runtime/References/AtomBaseReference.cs
- Packages/Core/Runtime/References/AtomReference.cs
> Added GetEvent and SetEvent functions to AtomReference

- Packages/Core/Editor/Editors/Variables/AtomVariableEditor.cs
- Packages/Core/Runtime/Variables/AtomVariable.cs
> Default Value For Changed and ChangedWithHistory

- Packages/Core/Runtime/ValueLists/BaseAtomValueList.cs
> Added StartCleared to ValueList

- README.md
Adding a little bit of clarity to installation for someone completely new to unity packages
> Adding a little bit of clarity to installation

- docs/README.md
- docs/introduction/faq.md
- website/i18n/en.json
- website/sidebars.json
The content is originally contributed by @thimo on Discord.
> Fix #130 Add FAQ to documentation pages

- Packages/BaseAtoms/Editor/AtomsSearchableAssetCreationMenu.cs
- Packages/Core/Editor/Editors/AtomGeneratorEditor.cs
- Packages/Core/Editor/Generator/RegenerateAllAtoms.cs
Implements #213. Included some minor clean up as well.
> Move atom search menu item

- Packages/BaseAtoms/Runtime/Collections/SerializableDictionary.cs
> Clear keys and values when clearing seriazlied dict

- Packages/Core/Runtime/VariableInstancers/AtomBaseVariableInstancer.cs
> Fixing FSM instancer where _base always is null

- Packages/Core/Runtime/StackTrace/StackTraceEntry.cs
when disabling atoms debug mode, StackTraceEntries are allocated, but their strings are never used.
this costs much performance in the InfinitiveWave Demo.
create many enemies and make them move. observe the unity profiler
> Lazy stacktrace toString conversion

- Packages/Core/Editor/Editors/AtomFolderEditor.cs
- Packages/Core/Editor/Editors/AtomGeneratorEditor.cs
- Packages/Core/Editor/Extensions/TypeExtensions.cs
- Packages/Core/Editor/Extensions/TypeExtensions.cs.meta
- Packages/Core/Editor/Generator/AtomGenerator.cs
> compatibility with dynamic assemblies and different namespace/class conditions

- CONTRIBUTING.md
- Packages/BaseAtoms/Documentation/README.md
- Packages/Core/Documentation/README.md
- Packages/FSM/Documentation/README.md
- Packages/Mobile/Documentation/README.md
- Packages/MonoHooks/Documentation/README.md
- Packages/SceneMgmt/Documentation/README.md
- Packages/Tags/Documentation/README.md
- Packages/UI/Documentation/README.md
- docs/introduction/faq.md
- docs/introduction/quick-start.md
- docs/tutorials/advanced-example.md
- website/core/Footer.js
- website/siteConfig.js
Due to the move to a new organization, the website URL's were out of date.
> Update website URL in docs

- CHANGELOG.md
- CONTRIBUTING.md
- Packages/Core/Editor/Generator/AtomGenerator.cs
This simple change will speed up atom generation via an AtomGenerator. The whole thing will only take 10 seconds instead of +1 minute.
> Speedup Atom Generation

- docs/tutorials/unirx.md
Updates the link in UniRx tutorial to fix a broken link.
> #279 Update link in UniRx tutorial

- Packages/Core/Runtime/Conditions/AtomCondition.cs
- Packages/Core/Runtime/Listeners/AtomBaseListener.cs
These changes allow the Conditions to properly serialize in Unity 2019.
> #253 Fix conditions not serializing in Unity 2019

- Packages/MonoHooks/Runtime/Hooks/OnAwakeHook.cs
- Packages/MonoHooks/Runtime/Hooks/VoidHook.cs
This commit adds the possibility to trigger mono hook events from an instaniater
> #271 Use event references in VoidHook and OnAwakeHook

- CHANGELOG.md
- Packages/BaseAtoms/package.json
- Packages/Core/package.json
- Packages/FSM/package.json
- Packages/InputSystem/package.json
- Packages/Mobile/package.json
- Packages/MonoHooks/package.json
- Packages/SceneMgmt/package.json
- Packages/Tags/package.json
- Packages/UI/package.json
- README.md
- docs/introduction/installation.md
- package-lock.json
- package.json
Updates all necessary files in preparation for the release of 4.4.5.
> Prepare for release of 4.4.5

- Packages/Core/Editor/Extensions/SerializedPropertyExtensions.cs
> fix: #363 enum property did not return int value, but index

- Packages/Core/Editor/Generator/AtomGenerator.cs
> fix: corrected IEquatable implementation check

- Packages/FSM/Runtime/FiniteStateMachine/FiniteStateMachineInstancer.cs
> Call base impl of ImplSpecificSetup() in FSM instancer

- Packages/BaseAtoms/Runtime/MonoBehaviourHelpers/SyncGameObjectToList.cs
> fixes syncgameobjecttolist adding object multiple times

- Packages/Core/Runtime/Variables/AtomVariable.cs
- Packages/FSM/Runtime/FiniteStateMachine/FiniteStateMachine.cs
Fixes: #402
I hope that there is no oversight on my end, but from my testing it seemed to be fine.
> make FSM compatible with disabled domain reload 

- Packages/Core/Runtime/Events/AtomEvent.cs
- Packages/Core/Runtime/ValueLists/AtomValueList.cs
- Packages/Core/Runtime/Variables/AtomVariable.cs
Fixes: #419 Fixes: #418 
Minor fix, for an inaccuracy of #403
> AtomValueList disabled domain reload compatibility

- docs/tutorials/events.md
I couldn't find a part in the documentation that indicated which was which in "Changed with history" callbacks FloatPair.
> [doc] Added informations to "Changed with history" documentation
